#!/bin/sh
# postinst script for tawd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    	mkdir -p /var/lib/tawd/AuctionHouse /var/lib/tawd/Audit \
    		/var/lib/tawd/Clan /var/lib/tawd/CreditShop /var/lib/tawd/Grove \
    		/var/lib/tawd/IGForum /var/lib/tawd/Petitions /var/lib/tawd/VirtualItems \
    		/var/log/tawd
    		
    	touch /var/log/tawd/crash_dump.txt
    		
    	if [ -f /lib/systemd/system/tawd.service ] ; then
    		systemctl daemon-reload
    		systemctl start tawd 
    	elif [ -f /etc/init.d/tawd ] ; then
	    	update-rc.d tawd defaults
	    	/etc/init.d/tawd start
	    fi
    	 
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
