#!/bin/sh
 	
if [ -f /lib/systemd/system/tawd.service ] ; then
	systemctl stop tawd 2>/dev/null
elif [ -f /etc/init.d/tawd ] ; then
	if /etc/init.d/tawd status
	then /etc/init.d/tawd stop >/dev/null
	fi
fi

exit 0